name: bidrag-statistikk
ingresses:
  - https://bidrag-statistikk.intern.nav.no
kafka:
  pool: nav-prod
kafka-topic-vedtak: bidrag.vedtak
kafka-topic-statistikk: bidrag.statistikk
spring-profiles: live,nais,database-legacy
azure:
  bidrag_vedtak_url: http://bidrag-vedtak.intern.nav.no
  bidrag_vedtak_scope: prod-gcp.bidrag.bidrag-vedtak
outbound-access-apps:
  - bidrag-vedtak
spec:
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi