name: bidrag-statistikk
ingresses:
  - https://bidrag-statistikk.intern.nav.no
kafka:
  pool: nav-prod
env:
  SPRING_PROFILES_ACTIVE: live,nais
  BIDRAG_VEDTAK_URL: http://bidrag-vedtak
  BIDRAG_VEDTAK_SCOPE: prod-gcp.bidrag.bidrag-vedtak
  TOPIC_STATISTIKK: bidrag.statistikk
  TOPIC_STATISTIKK_BIDRAG: bidrag.statistikk-bidrag
  TOPIC_VEDTAK: bidrag.vedtak
outbound-access-apps:
  - bidrag-vedtak
spec:
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi